# Generated by Django 4.0.3 on 2022-03-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=20)),
                ('category', models.IntegerField()),
                ('moviewline', models.CharField(max_length=50)),
                ('viewdate', models.DateTimeField()),
                ('diary', models.TextField()),
                ('moviewimg', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
