# Generated by Django 4.0.3 on 2022-03-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0002_rename_diary_moviews_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviews',
            name='viewdate',
            field=models.DateField(),
        ),
    ]
