# Generated by Django 4.0.3 on 2022-03-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0003_alter_moviews_viewdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviews',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
