# Generated by Django 4.0.3 on 2022-03-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0004_alter_moviews_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviews',
            name='moviewimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
