# Generated by Django 4.0.3 on 2022-03-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0006_alter_moviews_moviewimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviews',
            name='uploaduser',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
