# Generated by Django 4.0.3 on 2022-03-21 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0008_remove_moviews_uploaduser_moviews_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviews',
            name='id',
        ),
        migrations.AddField(
            model_name='moviews',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 8, 11, 18, 648001), primary_key=True, serialize=False),
        ),
    ]
