# Generated by Django 4.0.3 on 2022-03-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0009_remove_moviews_id_moviews_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviews',
            name='datetime',
        ),
        migrations.AddField(
            model_name='moviews',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
