# Generated by Django 4.0.3 on 2022-03-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0010_remove_moviews_datetime_moviews_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviews',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
