# Generated by Django 4.0.3 on 2022-03-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0011_alter_moviews_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviews',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
