# Generated by Django 4.0.3 on 2022-03-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0014_alter_moviews_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviews',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
